### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by back2dos** [MVCoconut/coconut.diffing#1]
Ideally should contain an example on how to create a coconut.ui backend with this.

**Comment by darmie** [comment]
Awesome!

I am looking forward to the docs.

Can't wait to wrap coconut around my UI framework.

**Comment by kevinresol** [comment]
huh why this is not closed by the commit?

**Comment by darmie** [comment]
It was closed, last I checked. It was probably reopened

**Comment by kevinresol** [comment]
> It was closed, last I checked. It was probably reopened

but then there should be a history showing in the thread?

**Comment by back2dos** [comment]
> huh why this is not closed by the commit?

The commit closing this is not on master yet ;)
